import re, sys
from pathlib import Path
import requests

DEFAULT_MODEL = "nousresearch/hermes-2-pro:free"

def fetch_pr(owner: str, repo: str, number: int):
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "pr-review-agent"}
    r = requests.get(f"https://api.github.com/repos/{owner}/{repo}/pulls/{number}", headers=headers, timeout=30)
    if r.status_code in (401,403): return None, str(r.status_code)
    r.raise_for_status()
    return r.json(), None

def fetch_diff(url: str):
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "pr-review-agent"}
    r = requests.get(url, headers=headers, timeout=30)
    return r.text if r.status_code == 200 else ""

def review(title, diff):
    added = diff.count("\n+")
    removed = diff.count("\n-")
    churn = added + removed
    files = len(re.findall(r"^diff --git", diff, re.M))
    risks = []
    ideas = []
    if re.search(r"password|secret|token|api[_-]?key", diff, re.I) and added > 0:
        risks.append("Possible credential or secret added in diff.")
    if re.search(r"innerHTML|eval\(|exec\(|system\(|subprocess\.call|shell=True", diff, re.I):
        risks.append("Potential code injection via innerHTML/eval/exec/system calls.")
    if re.search(r"SELECT .* FROM |INSERT INTO |UPDATE .* SET |DELETE FROM ", diff, re.I):
        risks.append("Raw SQL detected in diff — verify parameterization.")
    if re.search(r"TODO|FIXME|HACK", diff):
        ideas.append("Resolve or track TODO/FIXME/HACK comments before merge.")
    if files > 20:
        ideas.append("Large PR surface area — consider splitting for reviewability.")
    if churn > 2000:
        ideas.append("High churn detected — ensure tests and perf review are included.")
    if not risks:
        risks.append("No high-severity patterns detected in automated scan.")
    confidence = "High" if (len(risks) == 1 and files < 15 and churn < 1000) else "Medium"
    summary = f"PR touches {files} file(s) with ~{churn} line changes. Automated scan did not identify obvious critical issues; confidence set to {confidence} based on size and pattern coverage."
    return {"summary": summary, "risks": risks, "improvements": ideas, "confidence": confidence, "files": files, "churn": churn}

def render(pr, rv):
    out = [f"# PR Review: {pr.get('title','(no title')} #{pr.get('number','?')}", "", f"**URL:** {pr.get('html_url','')}", f"**Author:** {pr.get('user',{}).get('login','unknown')}", "", "## Summary", "", rv["summary"], "", "## Identified Risks", ""]
    for x in rv["risks"]: out.append(f"- {x}")
    out += ["", "## Improvement Suggestions", ""]
    for x in rv["improvements"]: out.append(f"- {x}")
    out += ["", "## Confidence", "", rv["confidence"], "", "## Metrics", "", f"- Files: {rv['files']}", f"- Churn: {rv['churn']}", "", "_Generated by pr-review-agent_"]
    return "\n".join(out)

def main(argv=None):
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--pr", required=True)
    p.add_argument("--output", default="-")
    p.add_argument("--model", default=DEFAULT_MODEL)
    args = p.parse_args(argv)
    owner = repo = number = None
    m = re.search(r"github\.com/([^/]+)/([^/]+)/pull/(\d+)", args.pr)
    if m: owner, repo, number = m.group(1), m.group(2), int(m.group(3))
    else:
        m = re.match(r"^([^/]+)/([^/]+)/(\d+)$", args.pr)
        if m: owner, repo, number = m.group(1), m.group(2), int(m.group(3))
    if not owner:
        print("Could not parse PR reference", file=sys.stderr); return 2
    pr, err = fetch_pr(owner, repo, number)
    if err: print(f"GitHub API error: {err}", file=sys.stderr); return 2
    diff_url = pr.get("diff_url") or pr.get("patch_url")
    diff = fetch_diff(diff_url) if diff_url else ""
    if not diff: print("No diff available", file=sys.stderr); return 2
    rv = review(pr.get("title",""), diff)
    md = render(pr, rv)
    if args.output == "-": print(md)
    else: Path(args.output).write_text(md, encoding="utf-8")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
